### PR TITLE
Implementing simplified PCAP filter definition.

### PR DESCRIPTION
**Pull request by gchux**
implements feature requests:
- #21
- #22 

---

## NEW environment variables:

- `PCAP_HOSTS` ( `tcpdumpw` flag: `hosts` ): takes a comma separated list of FQDNs, translates them into all IPv4 and IPv6 and applies `OR` to all IPs.
    - example: `1.example.com,2.example.com,3.example.com` *-[yields]->* `(host 1.1.1.1 or host 2.2.2.2 or host 3.3.3.3)`
- `PCAP_PORTS` ( `tcpdumpw` flag: `ports` ): takes a comma separated list of transport later addresses ( ports ) and applies `OR` to all ports.
    - **NOTE**: This one has no feature request, but it makes sense to also simplify transport layer filters.
    - example: `80,443` *-[yields]->* `(port 80 or port 443)`
- `PCAP_TCP_FLAGS` ( `tcpdumpw` flag: `tcp_flags` ): takes a comma separated list of lowercase TCP flags and applies,  `OR` to all flags, so that if ANY listed flag ( not all of them ) is set the packet will be captured.
    - example: `syn,ack`  *-[yields]->* `tcp[tcpflags] & (tcp-syn|tcp-ack) != 0)`

## Expected Behavior

- IF not defined, the default value for new env vars is `ALL`, which means that the corresponding filter(s) won't be applied.
- `Apply` operation of a filter provider will wrap the resulting filter in parenthesis.
- ALL filters will be applied `AND`ed agains each other and finally with `PCAP_FILTER`.
- IF ALL filters are provided, the final filter will be: `(PCAP_FILTER) and (PCAP_HOSTS) and (PCAP_PORTS) and (PCAP_TCP_FLAGS)`
    - if any filter is missing, then its corresponding contribution will be omitted; i/e, if `PCAP_TCP_FLAGS` is not set, then the resulting BPF filter will be: `(PCAP_FILTER) and (PCAP_HOSTS) and (PCAP_PORTS)`

## Sample Logs 

For the following environment variables:
- `PCAP_FILTER`=`tcp`
- `PCAP_HOSTS`=`metadata.google.internal`
- `PCAP_PORTS`=`80`
- `PCAP_TCP_FLAGS`=`syn`

> **expected filter**: `(tcp) and (host 169.254.169.254) and (port 80) and (tcp[tcpflags] & (tcp-syn) != 0)`

> the benefits of using a simplified/declarative process to build complex BPF filters should be evident: it allows humans and automations to be more efficient and less error-prone.

The following logs are expected:

> some values like `tcpdump` PID and `NIC` names will change, and presented just for completeness:

```
{
  "message": "using filter: DNSFilter[metadata.google.internal] => (host 169.254.169.254)",
}
{
  "message": "using filter: PortsFilter[80] => (port 80)",
}
{
  "message": "using filter: TCPFlagsFilter[syn] => (tcp[tcpflags] & (tcp-syn) != 0)",
}
...
[tcpdump] - 2024/09/30 17:04:57 EXEC(973014): /usr/bin/tcpdump -n -i ens4 /part__2_ens4__%Y%m%dT%H%M%S.pcap (tcp) and (host 169.254.169.254) and (port 80) and (tcp[tcpflags] & (tcp-syn) != 0)
...
[gopacket] - 2024/09/30 17:04:57 [2/ens4] - starting packet capture | filter: (tcp) and (host 169.254.169.254) and (port 80) and (tcp[tcpflags] & (tcp-syn) != 0)
```

### CODE REVIEW

**Comment by gchux** [comment]
## Implementation Details:

- `pcap-cli` only provides the interface that a `PcapFilterProvider` must adhere to, so it does not implement any filter.
- `pcap-cli` accepts a list of `PcapFilterProvider`s that will apply to every execution of any `PcapEngine`
    - which means that every time a client calls `Start(...)` on any engine, the filters will be re-applied
    - it is up to the `PcapFilterProvider` implementation to define if it wants to cache and return the same calculated filter every time or if it will calculate the filter every time `Get(...)/Apply(...)` are invoked; i/e: the result value of applying `PCAP_PORTS` may be desirable to be cached as it not expected to change, but the outcome of `PCAP_HOSTS` may not be cached to allow capturing change in `DNS` registers between PCAP executions.
- the list of filters passed to `pcap-cli` my be the same for all `PcapEngine`s as it will not mutate the input list of `PcapFilterProviders`
    - it also means that the client calling `Start(...)` on any `PcapEngine` may mutate the list to modify the list or any filter within the list as it requires; which means that the list of `PcapFilterProviders` is LIVE and not thread-safe.

**Comment by gchux** [comment]
if approved, we should probably target this feature for release `v1.2.0`

**Review by thomasmburke — APPROVED** [review]

**Comment by gchux** [comment]
@thomasmburke : as discussed, we now have the following new simple filters:

- `PCAP_L3_PROTOS`:  comma separated list of network layer protocols; it currently accepts [multiple forms of IPv4 and IPv6](https://github.com/gchux/cloud-run-tcpdump/blob/ft/simple-filters/tcpdumpw/pkg/filter/l3_proto_filter_provider.go#L40-L43). In general users may want to use some variation of: `ipv4,ipv6`.
- `PCAP_L4_PROTOS`:  comma separated list of transport layer protocols; it currently accepts [multiple forms of TCP and UDP](https://github.com/gchux/cloud-run-tcpdump/blob/ft/simple-filters/tcpdumpw/pkg/filter/l4_proto_filter_provider.go#L40-L43). In general users may want to use some variation of: `tcp,udp`.
- `PCAP_IPV4`: comma separated list of IPv4 addresses or IPv4 networks using CIDR notation.
- `PCAP_IPV6`: comma separated list of IPv6 addresses or IPv6 networks using CIDR notation.
- `PCAP_HOSTS`: which uses the DNS provider is merged alongside `PCAP_IPV4` and `PCAP_IPV6` to create a complete IP filter provider; the resulting filter:
    - resolves FQDNs to IPs ( including both IPv4 and IPv6 ) and merges them with RAW IPv4 and IPv6
    - guarantees all IPs are de-duplicated, meaning that no IP will be repeated in the filter, so every IP regardless of the version will appear only once.
    - prefers networks over individual IP addresses; which means that all IPs ( including the ones resulting from DNS resolution ) will be tested against all provided networks; if a any networks contain any IPs, the contained IPs will be discarded in favor of networks to keep the BPF filter DRY.
        - see: https://github.com/gchux/cloud-run-tcpdump/blob/ft/simple-filters/tcpdumpw/pkg/filter/ip_filter_provider.go#L66-L80 

> see `init` script: https://github.com/gchux/cloud-run-tcpdump/blob/ft/simple-filters/scripts/init#L97-L112

> see `tcpdumpw` startup script: https://github.com/gchux/cloud-run-tcpdump/blob/ft/simple-filters/scripts/start_tcpdumpw#L30-L37

[if `PCAP_FILTER` is provided, then no simple filters will be applied](https://github.com/gchux/cloud-run-tcpdump/blob/ft/simple-filters/tcpdumpw/main.go#L509-L523) and its value will be used as-is; which means that the only way to use simple filters is to not define a value for `PCAP_FILTER` or set it to `DISABLED`.

`PCAP_L3_PROTOS` and `PCAP_L4_PROTOS` always yield a value, which means that even If no simple filters and no `PCAP_FILTER` are available, then `PCAP_L3_PROTOS` and `PCAP_L4_PROTOS` will always contribute with their respective default values:
- `PCAP_L3_PROTOS` => [`ip or ip6`](https://github.com/gchux/cloud-run-tcpdump/blob/ft/simple-filters/tcpdumpw/pkg/filter/l3_proto_filter_provider.go#L19)
- `PCAP_L4_PROTOS` => [`tcp or udp`](https://github.com/gchux/cloud-run-tcpdump/blob/ft/simple-filters/tcpdumpw/pkg/filter/l4_proto_filter_provider.go#L19)

In general, the default filter if no simple filter or `PCAP_FILTER` are provided will be the catch-all [`(tcp or udp) and (ip or ip6)`](https://github.com/gchux/cloud-run-tcpdump/blob/ft/simple-filters/tcpdumpw/main.go#L112)

`PCAP_FILTER` can now be an advanced configuration, in favor of simple filters.
 
image

**Comment by gchux** [comment]
@thomasmburke does this implementation fully captures our conversation about simple filters?

**Pull request merged**
